name: altur
description: "Altur Teknoloji - Study Case"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  #state management
  get: ^4.7.2

  #local db
  sqflite: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #notification
  flutter_local_notifications: ^19.0.0

  #widget
  fl_chart: ^0.70.2
  animated_bottom_navigation_bar: ^1.4.0

  #utilty
  intl: ^0.20.2
  path: ^1.9.0
  turkish: ^0.2.1
  permission_handler: ^11.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  image: assets/splash/ic_splash.png  # Splash icon için resim
  color: "#ffffff"  # Arka plan rengi
  android: true
  ios: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_app.png"  # Kullanmak istediğin ikonun yolu
  adaptive_icon_background: "#ffffff"  # Android adaptive icon arka planı
  adaptive_icon_foreground: "assets/icons/ic_app.png"  # Adaptive foreground


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/splash/


